/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wayne.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.wayne.struts.form.UserForm;

/**
 * MyEclipse Struts Creation date: 10-20-2018
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/loginAndlogout" name="userForm" scope="request"
 */
public class LoginAndlogoutAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	// 处理登录请求
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		if ("123".equals(userForm.getPassword())) {
			return mapping.findForward("loginok");
		} else {
			//局部跳转
			//return mapping.findForward("loginerr");
			//全局跳转
			return mapping.findForward("err");
		}
	}

	// 处理退出请求
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// UserForm userForm = (UserForm) form;// TODO Auto-generated method
		// stub
		// return null;
		return mapping.findForward("loginerr");
	}
}