/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 10-21-2018
 * 
 * XDoclet definition:
 * @struts.action path="/registerAction" name="userForm" scope="request"
 */
public class RegisterAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm userForm = (DynaActionForm) form;// TODO Auto-generated method stub
//		return null;
		String name = userForm.getString("name").toString();
		String password = userForm.getString("password").toString();
		String email=userForm.getString("email").toString();
		System.out.println(name+" "+password+" "+email+" ");
		
		return mapping.findForward("ok");
	}
}